package presentation.marketing.controller;

import presentation.marketing.view.ProcessMarketingViewModifyCreditControllerService;

public class ProcessMarketingViewModifyCreditController implements ProcessMarketingViewModifyCreditControllerService{

}
