package presentation.marketing.controller;

import presentation.marketing.view.ProcessMarketingViewProfileControllerService;

public class ProcessMarketingViewProfileController implements ProcessMarketingViewProfileControllerService{

}
