package presentation.marketing.controller;

import presentation.marketing.view.ProcessMarketingViewDesignLevelControllerService;

public class ProcessMarketingViewDesignLevelController implements ProcessMarketingViewDesignLevelControllerService{

}
