package presentation.marketing.controller;

import presentation.marketing.view.ProcessMarketingViewaDesignStrategyControllerService;

public class ProcessMarketingViewDesignStrategyController implements ProcessMarketingViewaDesignStrategyControllerService{

}
