package presentation.marketing.controller;

import presentation.marketing.view.ProcessMarketingViewProcessOrderControllerService;

public class ProcessMarketingViewProcessOrderController implements ProcessMarketingViewProcessOrderControllerService{

}
