package presentation.marketing.controller;

import presentation.marketing.view.ProcessMarketingViewDesignPrivilegeControllerService;

public class ProcessMarketingViewDesignPrivilegeController implements ProcessMarketingViewDesignPrivilegeControllerService{

}
